image: alpine:3.18

stages:
  - build
  - test
  - deploy

.create_config:
  stage: build
  before_script:
    - apk add --no-cache gcc musl-dev make flex bison linux-headers elfutils-dev openssl-dev

linux-kernel 1/2:
  stage: build
  needs: ["before"]
  script:
    - wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
    - tar xfa linux-6.6.6.tar.xz
    - cd linux-6.6.6
    - make defconfig
  cache:
    paths:
      - .config


linux-kernel 2/2:
  stage: build
  needs: ["linux-kernel 1/2"]
  script:
    - wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
    - tar xfa linux-6.6.6.tar.xz
    - cd linux-6.6.6
    - make defconfig
    - start=`date +%s`
    - make -j1
    - end=`date +%s`
    - echo "Executed in `expr $end - $start` seconds."
    - start=`date +%s`
    - make -j2
    - end=`date +%s`
    - echo "Executed in `expr $end - $start` seconds."
    - start=`date +%s`
    - make -j4
    - end=`date +%s`
    - echo "Executed in `expr $end - $start` seconds."
    - start=`date +%s`
    - make -j8
    - end=`date +%s`
    - echo "Executed in `expr $end - $start` seconds."

hello-world:
  stage: build
  script:
    - start=`date +%s%N`
    - echo "Hello world"
    - end=`date +%s%N`
    - echo "Execution time was `expr $end - $start` nanoseconds."

pages:
  stage: deploy
  script:
    - echo "Hello world"
    - mkdir public
  artifacts:
    paths:
      - public
    expire_in: 14 days
  only:
    - main
