name: build

'on':
    pull_request:
    push:
        branches:
          - main

jobs:
    build-linux-kernel:
        runs-on: alpine-${{ matrix.alpine_version }}
        name: Alpine-${{ matrix.alpine_version }}
        strategy:
            fail-fast: false
            matrix:
                ubuntu_version: [3.18]
                shared: [ON, OFF]

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0


          - name: pre-os
            run: |
                sudo apk add --no-cache gcc musl-dev make flex bison linux-headers elfutils-dev openssl-dev perl
                wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
                tar xfa linux-6.6.6.tar.xz

          - name: linux-kernel - single proc
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j1
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."

          - name: linux-kernel - two procs
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j2
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."

          - name: linux-kernel - four procs
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j4
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."

          - name: Build
            run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    hello-world:
        runs-on: alpine-${{ matrix.alpine_version }}
        name: Alpine-${{ matrix.alpine_version }}
        strategy:
            fail-fast: false
            matrix:
                ubuntu_version: [3.18]
                shared: [ON, OFF]

        steps:
          - name: hello-world
            run: |
                start=`date +%s%N`
                echo "Hello world"
                end=`date +%s%N`
                echo "Execution time was `expr $end - $start` nanoseconds." 
