name: build

'on':
    pull_request:
    push:
        branches:
          - main

jobs:
    build-linux-kernel-1:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - uses: jirutka/setup-alpine@v1
            with:
                branch: v3.18

          - name: pre-os
            run: |
                apk add --no-cache gcc musl-dev make flex bison linux-headers elfutils-dev openssl-dev perl
                wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
                tar xfa linux-6.6.6.tar.xz
            shell: alpine.sh --root {0}

          - name: linux-kernel - single proc
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j1
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."
            shell: alpine.sh --root {0}

    build-linux-kernel-2:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - uses: jirutka/setup-alpine@v1
            with:
                branch: v3.18

          - name: pre-os
            run: |
                apk add --no-cache gcc musl-dev make flex bison linux-headers elfutils-dev openssl-dev perl
                wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
                tar xfa linux-6.6.6.tar.xz
            shell: alpine.sh --root {0}

          - name: linux-kernel - two procs
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j2
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."
            shell: alpine.sh --root {0}

    build-linux-kernel-3:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - uses: jirutka/setup-alpine@v1
            with:
                branch: v3.18

          - name: pre-os
            run: |
                apk add --no-cache gcc musl-dev make flex bison linux-headers elfutils-dev openssl-dev perl
                wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
                tar xfa linux-6.6.6.tar.xz
            shell: alpine.sh --root {0}

          - name: linux-kernel - four procs
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j4
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."
            shell: alpine.sh --root {0}

    build-linux-kernel-4:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - uses: jirutka/setup-alpine@v1
            with:
                branch: v3.18

          - name: pre-os
            run: |
                apk add --no-cache gcc musl-dev make flex bison linux-headers elfutils-dev openssl-dev perl
                wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.6.tar.xz
                tar xfa linux-6.6.6.tar.xz
            shell: alpine.sh --root {0}

          - name: linux-kernel - NPROC
            run: |
                cd linux-6.6.6
                make clean defconfig
                start=`date +%s`
                make -j$(getconf _NPROCESSORS_ONLN)
                end=`date +%s`
                echo "Executed in `expr $end - $start` seconds."
            shell: alpine.sh --root {0}

    hello-world:
        runs-on: ubuntu-latest
        steps:
          - uses: jirutka/setup-alpine@v1
            with:
                branch: v3.18

          - name: hello-world
            run: |
                start=`date +%s%N`
                echo "Hello world"
                end=`date +%s%N`
                echo "Execution time was `expr $end - $start` nanoseconds." 
            shell: alpine.sh --root {0}
